# Домашнее задание

### Задание 1

In [ ]:
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [5]:
import numpy as np

def new_array(n):
    first_arange = np.arange(-n+1, 0+1)
    second_arange = first_arange*(-1)
    return second_arange

elements = 20
new_array(elements)

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

### Задание 2

In [ ]:
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [14]:
import numpy as np

def matrix():
    first_arange = np.arange(-n+1, 0+1)
    second_arange = first_arange*(-1)
    result = np.diag(second_arange)
    return result

# число элементов в матрице
n = 50

matrix = matrix() # Я же могу переменную и функцию сделать одноименными в данном задании? Или это не лучшая практика?

print(matrix)

# Подсчёт суммы значений матрицы по диагонали (я в старой домашней работе такой же код использовал, на мой взгляд прекрасно подходит для такой задачи)
total = sum(matrix[i][i] for i in range(n))
print(total)

[[49  0  0 ...  0  0  0]
 [ 0 48  0 ...  0  0  0]
 [ 0  0 47 ...  0  0  0]
 ...
 [ 0  0  0 ...  2  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0  0]]
1225


### Задание 3

In [ ]:
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3